# Generated by Django 4.2.16 on 2024-09-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Title',
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, choices=[('miss', 'Miss'), ('ms', 'Ms'), ('mrs', 'Mrs'), ('mr', 'Mr')], max_length=10, verbose_name='Title'),
        ),
    ]
