# Generated by Django 4.2.16 on 2024-09-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='people_num',
            new_name='number_of_guests',
        ),
    ]
