# Generated by Django 4.2.16 on 2024-10-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
