# Generated by Django 5.1.1 on 2024-10-01 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 20, 15, 13, 377554)),
        ),
    ]
