# Generated by Django 5.1.1 on 2024-10-01 21:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 21, 35, 32, 934125)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(choices=[('1', 'Reserved'), ('2', 'Available')], default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
    ]
