# Generated by Django 5.1.1 on 2024-10-01 21:46

import booking.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_customer_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=booking.models.Customer, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='booking.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 21, 46, 26, 538449)),
        ),
    ]
