# Generated by Django 5.1.1 on 2024-10-01 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_customer_alter_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 21, 30, 4, 120212)),
        ),
    ]
