# Generated by Django 5.1.1 on 2024-10-01 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 21, 31, 9, 437798)),
        ),
    ]
