# Generated by Django 5.1.1 on 2024-10-06 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 12, 37, 21, 256643)),
        ),
    ]
