# Generated by Django 5.1.1 on 2024-10-07 09:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_table_number_of_guests_booking_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 9, 56, 17, 708551)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
