# Generated by Django 5.1.1 on 2024-10-07 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_remove_booking_customer_remove_booking_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 10, 3, 24, 378862)),
        ),
    ]
