# Generated by Django 5.1.1 on 2024-10-07 10:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_booking_customer_alter_booking_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 10, 4, 29, 317088)),
        ),
    ]
