# Generated by Django 5.1.1 on 2024-10-07 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_booking_customer_alter_booking_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 22, 48, 41, 67486)),
        ),
    ]
