# Generated by Django 4.2.16 on 2024-10-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_booking_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
