# Generated by Django 4.2.16 on 2024-10-11 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_booking_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='draft',
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 1, 2, 48, 725805)),
        ),
    ]
