# Generated by Django 4.2.16 on 2024-10-11 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_remove_booking_cancelled_remove_booking_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 12, 52, 52, 973939)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
