# Generated by Django 4.2.16 on 2024-10-11 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_booking_draft_alter_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 14, 8, 31, 561765)),
        ),
    ]
