# Generated by Django 4.2.16 on 2024-10-11 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_booking_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_dateandtime_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_dateandtime_start',
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 14, 22, 42, 202841)),
        ),
    ]
