# Generated by Django 4.2.16 on 2024-09-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailaddress_idx_upper_email'),
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailConfirmationView',
            fields=[
                ('emailconfirmation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.emailconfirmation')),
            ],
            bases=('account.emailconfirmation',),
        ),
    ]
