# Generated by Django 4.2.16 on 2024-09-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_customemailconfirmationview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
