# Generated by Django 4.2.16 on 2024-09-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_remove_review_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomEmailConfirmationView',
        ),
    ]
