# Generated by Django 4.2.16 on 2024-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_review_ip_review_rating_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
