# Generated by Django 4.2.16 on 2024-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
