# Generated by Django 4.2.16 on 2024-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_remove_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
