# Generated by Django 5.1.1 on 2024-10-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
    ]
