# Generated by Django 5.1.1 on 2024-10-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_remove_review_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
