# Generated by Django 5.1.1 on 2024-10-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_location_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
